// <auto-generated />
namespace HospitalManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class FixMedicalRecord1to1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixMedicalRecord1to1));
        
        string IMigrationMetadata.Id
        {
            get { return "202605310935552_FixMedicalRecord1to1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
